### ISSUE TITLE
code

### ISSUE THREAD

**Issue by VenRay** [annahung31/MIdiNet-by-pytorch#4]
the code is too disappointment!

**Comment by annahung31** [comment]
anything I can help?

**Comment by jerekeith2** [comment]
Your code throws errors. Acknowledge Issue #3 and fix the code so that it runs without errors after cloning the repo.

**Comment by VenRay** [comment]
do you have chord datasets?

**Comment by annahung31** [comment]
Hi,  @2016180202027 ,
It's sorry that I cannot give you the dataset directly due to the copy right issue.
Still you can use the tool in the following to parse it.
https://github.com/wayne391/Symbolic-Musical-Datasets/blob/master/theorytab/utils/theorytab_crawler.ipynb
